name: build

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout Source Code
        uses: actions/checkout@v4
      -
        name: Docker QEmu Setup
        uses: docker/setup-qemu-action@v3
      -
        name: Docker Buildx Setup
        uses: docker/setup-buildx-action@v3
      -
        name: Docker Login
        uses: docker/login-action@v3
        if: github.ref == 'refs/heads/master'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Docker Build & Push
        uses: docker/build-push-action@v3
        with:
          # Only publish new images when building the master branch
          push: ${{ github.ref == 'refs/heads/master' }}
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/nextcloud-cronjob:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/nextcloud-cronjob:${GITHUB_REF#refs/tags/}
      -
        name: Update Repository Description
        uses: peter-evans/dockerhub-description@v3
        if: github.ref == 'refs/heads/master'
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKERHUB_REPOSITORY: ${{ secrets.DOCKERHUB_USERNAME }}/nextcloud-cronjob
